// import local components
export { default as LoginArea } from "./components/LoginArea.vue"
export { default as ListWithImages } from "./components/ListWithImages.vue"
export { default as RegisterForm } from "./components/RegisterForm.vue"

// import settings-components
export { default as CmdWebsite } from "./components/CmdWebsite.vue"
export { default as CmdToggleDarkModeSettings } from "./components/editmode/component-settings/CmdToggleDarkModeSettings.vue"
export { default as CmdSocialNetworksSettings } from "./components/editmode/component-settings/CmdSocialNetworksSettings.vue"
export { default as CmdThumbnailScrollerSettings } from "./components/editmode/component-settings/CmdThumbnailScrollerSettings.vue"
export { default as ContactFormSettings } from "./components/editmode/component-settings/ContactFormSettings.vue"
export { default as CmdSlideshowSettings } from "./components/editmode/component-settings/CmdSlideshowSettings.vue"
export { default as CmdListOfLinksSettings } from "./components/editmode/component-settings/CmdListOfLinksSettings.vue"
export { default as CmdLinkItemSettings } from "./components/editmode/component-settings/CmdLinkItemSettings.vue"
export { default as CmdOpeningHoursSettings } from "./components/editmode/component-settings/CmdOpeningHoursSettings.vue"
export { default as CmdAddressDataSettings } from "./components/editmode/component-settings/CmdAddressDataSettings.vue"
export { default as CmdAddressDataItemSettings } from "./components/editmode/component-settings/CmdAddressDataItemSettings.vue"
export { default as CmdImageGallerySettings } from "./components/editmode/component-settings/CmdImageGallerySettings.vue"
export { default as CmdImageSettings } from "./components/editmode/component-settings/CmdImageSettings.vue"
export { default as CmdHeadlineSettings } from "./components/editmode/component-settings/CmdHeadlineSettings.vue"
export { default as CmdTextImageBlockSettings } from "./components/editmode/component-settings/CmdTextImageBlockSettings.vue"
export { default as SectionSettings } from "./components/editmode/component-settings/SectionSettings.vue"
export { default as CmdContainerSettings } from "./components/editmode/component-settings/CmdContainerSettings.vue"
export { default as InnerWrapper } from "./components/InnerWrapper.vue"
export { default as ContentSection } from "./components/ContentSection.vue"
export { default as RenderComponents } from "./components/RenderComponents.vue"
export { default as PageWrapper } from "./components/PageWrapper.vue"
export { default as EditModeSectionWrapper } from "./components/editmode/EditModeSectionWrapper.vue"
export { default as PageSchwerpunkte } from "./components/PageSchwerpunkte.vue"
